"""
Condensed invariant polynomials
Source: output
Condensation: P -> P0+dP, Mz -> Mz0+dMz
Generated by isocond
"""

import sympy as sp

# Original coefficient symbols
alpha1, alpha2, alpha3, alpha4, alpha5, alpha6, alpha7, alpha8, alpha9, alpha10, alpha11, alpha12, alpha13, alpha14, alpha15, alpha16, alpha17, alpha18, alpha19, alpha20, alpha21, alpha22, alpha23, alpha24, alpha25, alpha26, alpha27, alpha28, alpha29, alpha30, alpha31, alpha32, alpha33, alpha34, alpha35, alpha36, alpha37, alpha38, alpha39, alpha40, alpha41, alpha42, alpha43, alpha44, alpha45, alpha46, alpha47, alpha48, alpha49, alpha50, alpha51, alpha52, alpha53, alpha54, alpha55, alpha56, alpha57, alpha58, alpha59, alpha60, alpha61, alpha62, alpha63, alpha64, alpha65, alpha66, alpha67, alpha68, alpha69, alpha70, alpha71, alpha72, alpha73, alpha74, alpha75, alpha76, alpha77, alpha78, alpha79, alpha80, alpha81, alpha82, alpha83, alpha84, alpha85, alpha86, alpha87, alpha88, alpha89, alpha90, alpha91, alpha92, alpha93, alpha94 = sp.symbols("alpha1 alpha2 alpha3 alpha4 alpha5 alpha6 alpha7 alpha8 alpha9 alpha10 alpha11 alpha12 alpha13 alpha14 alpha15 alpha16 alpha17 alpha18 alpha19 alpha20 alpha21 alpha22 alpha23 alpha24 alpha25 alpha26 alpha27 alpha28 alpha29 alpha30 alpha31 alpha32 alpha33 alpha34 alpha35 alpha36 alpha37 alpha38 alpha39 alpha40 alpha41 alpha42 alpha43 alpha44 alpha45 alpha46 alpha47 alpha48 alpha49 alpha50 alpha51 alpha52 alpha53 alpha54 alpha55 alpha56 alpha57 alpha58 alpha59 alpha60 alpha61 alpha62 alpha63 alpha64 alpha65 alpha66 alpha67 alpha68 alpha69 alpha70 alpha71 alpha72 alpha73 alpha74 alpha75 alpha76 alpha77 alpha78 alpha79 alpha80 alpha81 alpha82 alpha83 alpha84 alpha85 alpha86 alpha87 alpha88 alpha89 alpha90 alpha91 alpha92 alpha93 alpha94")

# Static (condensed) variable symbols
P0, Mz0 = sp.symbols("P0 Mz0")

# Dynamic variable symbols
dP, dMz, ε, Qx, Qy, Mx, My = sp.symbols("dP dMz ε Qx Qy Mx My")

# New effective coefficients
beta1 = Mz0**6*alpha90 + Mz0**4*P0**2*alpha72 + Mz0**4*alpha26 + Mz0**2*P0**4*alpha65 + Mz0**2*P0**2*alpha19 + Mz0**2*alpha5 + P0**6*alpha63 + P0**4*alpha17 + P0**2*alpha3
beta2 = 2*Mz0*(3*Mz0**4*alpha90 + 2*Mz0**2*P0**2*alpha72 + 2*Mz0**2*alpha26 + P0**4*alpha65 + P0**2*alpha19 + alpha5)
beta3 = Mz0**4*alpha43 + Mz0**2*P0**2*alpha36 + Mz0**2*alpha10 + P0**4*alpha34 + P0**2*alpha8 + alpha1
beta4 = 2*P0*(Mz0**4*alpha72 + 2*Mz0**2*P0**2*alpha65 + Mz0**2*alpha19 + 3*P0**4*alpha63 + 2*P0**2*alpha17 + alpha3)
beta5 = 15*Mz0**4*alpha90 + 6*Mz0**2*P0**2*alpha72 + 6*Mz0**2*alpha26 + P0**4*alpha65 + P0**2*alpha19 + alpha5
beta6 = 2*Mz0*(2*Mz0**2*alpha43 + P0**2*alpha36 + alpha10)
beta7 = Mz0**4*alpha60 + Mz0**2*P0**2*alpha53 + Mz0**2*alpha15 + P0**4*alpha51 + P0**2*alpha13 + alpha2
beta8 = Mz0**4*alpha72 + 6*Mz0**2*P0**2*alpha65 + Mz0**2*alpha19 + 15*P0**4*alpha63 + 6*P0**2*alpha17 + alpha3
beta9 = Mz0**4*alpha84 + Mz0**2*P0**2*alpha69 + Mz0**2*alpha23 + P0**4*alpha64 + P0**2*alpha18 + alpha4
beta10 = Mz0**4*alpha91 + Mz0**2*P0**2*alpha73 + Mz0**2*alpha27 + P0**4*alpha66 + P0**2*alpha20 + alpha6
beta11 = 4*Mz0*P0*(2*Mz0**2*alpha72 + 2*P0**2*alpha65 + alpha19)
beta12 = Mz0*P0*(Mz0**2*alpha76 + P0**2*alpha67 + alpha21)
beta13 = 2*P0*(Mz0**2*alpha36 + 2*P0**2*alpha34 + alpha8)
beta14 = 6*Mz0**2*alpha43 + P0**2*alpha36 + alpha10
beta15 = 2*Mz0*(2*Mz0**2*alpha60 + P0**2*alpha53 + alpha15)
beta16 = 2*Mz0*(2*Mz0**2*alpha72 + 6*P0**2*alpha65 + alpha19)
beta17 = 2*Mz0*(2*Mz0**2*alpha84 + P0**2*alpha69 + alpha23)
beta18 = 2*Mz0*(2*Mz0**2*alpha91 + P0**2*alpha73 + alpha27)
beta19 = 4*Mz0*(5*Mz0**2*alpha90 + P0**2*alpha72 + alpha26)
beta20 = Mz0*(Mz0**2*alpha76 + 3*P0**2*alpha67 + alpha21)
beta21 = Mz0**2*alpha32 + P0**2*alpha30 + alpha7
beta22 = Mz0**2*alpha36 + 6*P0**2*alpha34 + alpha8
beta23 = Mz0**2*alpha40 + P0**2*alpha35 + alpha9
beta24 = Mz0**2*alpha44 + P0**2*alpha37 + alpha11
beta25 = 4*Mz0*P0*alpha36
beta26 = Mz0*P0*alpha38
beta27 = P0*(3*Mz0**2*alpha76 + P0**2*alpha67 + alpha21)
beta28 = 2*P0*(6*Mz0**2*alpha72 + 2*P0**2*alpha65 + alpha19)
beta29 = 2*P0*(Mz0**2*alpha53 + 2*P0**2*alpha51 + alpha13)
beta30 = 4*P0*(Mz0**2*alpha65 + 5*P0**2*alpha63 + alpha17)
beta31 = 2*P0*(Mz0**2*alpha69 + 2*P0**2*alpha64 + alpha18)
beta32 = 2*P0*(Mz0**2*alpha73 + 2*P0**2*alpha66 + alpha20)
beta33 = -2*(Mz0**2*alpha86 + P0**2*alpha70 - 2*alpha25)
beta34 = 15*Mz0**2*alpha90 + P0**2*alpha72 + alpha26
beta35 = 3*Mz0**2*alpha76 + 3*P0**2*alpha67 + alpha21
beta36 = 6*Mz0**2*alpha60 + P0**2*alpha53 + alpha15
beta37 = 6*Mz0**2*alpha72 + 6*P0**2*alpha65 + alpha19
beta38 = 6*Mz0**2*alpha84 + P0**2*alpha69 + alpha23
beta39 = 6*Mz0**2*alpha91 + P0**2*alpha73 + alpha27
beta40 = Mz0**2*alpha49 + P0**2*alpha47 + alpha12
beta41 = Mz0**2*alpha53 + 6*P0**2*alpha51 + alpha13
beta42 = Mz0**2*alpha57 + P0**2*alpha52 + alpha14
beta43 = Mz0**2*alpha61 + P0**2*alpha54 + alpha16
beta44 = Mz0**2*alpha65 + 15*P0**2*alpha63 + alpha17
beta45 = Mz0**2*alpha69 + 6*P0**2*alpha64 + alpha18
beta46 = Mz0**2*alpha73 + 6*P0**2*alpha66 + alpha20
beta47 = Mz0**2*alpha80 + P0**2*alpha68 + alpha22
beta48 = Mz0**2*alpha85 + Mz0**2*alpha86 + P0**2*alpha70 + P0**2*alpha71 + alpha24 + alpha25
beta49 = Mz0**2*alpha85 + P0**2*alpha71 + alpha24 + 3*alpha25
beta50 = Mz0**2*alpha92 + P0**2*alpha74 + alpha28
beta51 = 4*Mz0*P0*alpha53
beta52 = Mz0*P0*alpha55
beta53 = 8*Mz0*P0*alpha65
beta54 = 3*Mz0*P0*alpha67
beta55 = 4*Mz0*P0*alpha69
beta56 = 8*Mz0*P0*alpha72
beta57 = 4*Mz0*P0*alpha73
beta58 = Mz0*P0*alpha75
beta59 = 3*Mz0*P0*alpha76
beta60 = Mz0*P0*alpha77
beta61 = 2*Mz0*alpha32
beta62 = 2*Mz0*alpha36
beta63 = Mz0*alpha38
beta64 = 2*Mz0*alpha40
beta65 = 4*Mz0*alpha43
beta66 = 2*Mz0*alpha44
beta67 = 2*P0*alpha30
beta68 = 4*P0*alpha34
beta69 = 2*P0*alpha35
beta70 = 2*P0*alpha36
beta71 = 2*P0*alpha37
beta72 = P0*alpha38
beta73 = -4*Mz0*alpha86
beta74 = -4*P0*alpha70
beta75 = -2*alpha42
beta76 = 2*Mz0*(alpha85 + alpha86)
beta77 = 2*Mz0*alpha49
beta78 = 2*Mz0*alpha53
beta79 = Mz0*alpha55
beta80 = 2*Mz0*alpha57
beta81 = 4*Mz0*alpha60
beta82 = 2*Mz0*alpha61
beta83 = 2*Mz0*alpha65
beta84 = Mz0*alpha67
beta85 = 2*Mz0*alpha69
beta86 = 4*Mz0*alpha72
beta87 = 2*Mz0*alpha73
beta88 = Mz0*alpha75
beta89 = 3*Mz0*alpha76
beta90 = Mz0*alpha77
beta91 = 2*Mz0*alpha80
beta92 = 4*Mz0*alpha84
beta93 = 2*Mz0*alpha85
beta94 = 6*Mz0*alpha90
beta95 = 4*Mz0*alpha91
beta96 = 2*Mz0*alpha92
beta97 = 2*P0*(alpha70 + alpha71)
beta98 = 2*P0*alpha47
beta99 = 4*P0*alpha51
beta100 = 2*P0*alpha52
beta101 = 2*P0*alpha53
beta102 = 2*P0*alpha54
beta103 = P0*alpha55
beta104 = 6*P0*alpha63
beta105 = 4*P0*alpha64
beta106 = 4*P0*alpha65
beta107 = 4*P0*alpha66
beta108 = 3*P0*alpha67
beta109 = 2*P0*alpha68
beta110 = 2*P0*alpha69
beta111 = 2*P0*alpha71
beta112 = 2*P0*alpha72
beta113 = 2*P0*alpha73
beta114 = 2*P0*alpha74
beta115 = P0*alpha75
beta116 = P0*alpha76
beta117 = P0*alpha77
beta118 = alpha29
beta119 = alpha30
beta120 = alpha31
beta121 = alpha32
beta122 = alpha33
beta123 = alpha34
beta124 = alpha35
beta125 = alpha36
beta126 = alpha37
beta127 = alpha38
beta128 = alpha39
beta129 = alpha40
beta130 = alpha41
beta131 = alpha41 + alpha42
beta132 = alpha43
beta133 = alpha44
beta134 = alpha45
beta135 = -2*alpha59
beta136 = -2*alpha70
beta137 = -2*(alpha82 - 12*alpha83)
beta138 = -2*(alpha82 - 4*alpha83)
beta139 = -2*alpha86
beta140 = -2*(alpha88 - 12*alpha89)
beta141 = -2*(alpha88 - 4*alpha89)
beta142 = 2*alpha81 + alpha82 + 18*alpha83
beta143 = 2*alpha81 + alpha82 + 6*alpha83
beta144 = 2*alpha87 + alpha88 + 18*alpha89
beta145 = 2*alpha87 + alpha88 + 6*alpha89
beta146 = alpha46
beta147 = alpha47
beta148 = alpha48
beta149 = alpha49
beta150 = alpha50
beta151 = alpha51
beta152 = alpha52
beta153 = alpha53
beta154 = alpha54
beta155 = alpha55
beta156 = alpha56
beta157 = alpha57
beta158 = alpha58
beta159 = alpha58 + alpha59
beta160 = alpha60
beta161 = alpha61
beta162 = alpha62
beta163 = alpha63
beta164 = alpha64
beta165 = alpha65
beta166 = alpha66
beta167 = alpha67
beta168 = alpha68
beta169 = alpha69
beta170 = alpha70 + alpha71
beta171 = alpha71
beta172 = alpha72
beta173 = alpha73
beta174 = alpha74
beta175 = alpha75
beta176 = alpha76
beta177 = alpha77
beta178 = alpha78 + 11*alpha79
beta179 = 3*(alpha78 + 15*alpha79)
beta180 = 3*(alpha78 + 5*alpha79)
beta181 = alpha78 + 9*alpha79
beta182 = alpha80
beta183 = alpha81 + 11*alpha83
beta184 = alpha81 + 9*alpha83
beta185 = alpha81 + alpha82 + 3*alpha83
beta186 = alpha81 + alpha82 + alpha83
beta187 = alpha84
beta188 = alpha85
beta189 = alpha85 + alpha86
beta190 = alpha87 + 11*alpha89
beta191 = alpha87 + 9*alpha89
beta192 = alpha87 + alpha88 + 3*alpha89
beta193 = alpha87 + alpha88 + alpha89
beta194 = alpha90
beta195 = alpha91
beta196 = alpha92
beta197 = alpha93 + 11*alpha94
beta198 = 3*(alpha93 + 15*alpha94)
beta199 = 3*(alpha93 + 5*alpha94)
beta200 = alpha93 + 9*alpha94

# New invariants
invariants = [
    1,  # deg 0
    dMz,  # deg 1
    ε,  # deg 1
    dP,  # deg 1
    dMz**2,  # deg 2
    dMz*ε,  # deg 2
    ε**2,  # deg 2
    dP**2,  # deg 2
    Qx**2 + Qy**2,  # deg 2
    Mx**2 + My**2,  # deg 2
    dMz*dP,  # deg 2
    Mx*Qx + My*Qy,  # deg 2
    dP*ε,  # deg 2
    dMz**2*ε,  # deg 3
    dMz*ε**2,  # deg 3
    dMz*dP**2,  # deg 3
    Qx**2*dMz + Qy**2*dMz,  # deg 3
    Mx**2*dMz + My**2*dMz,  # deg 3
    dMz**3,  # deg 3
    Mx*Qx*dP + My*Qy*dP,  # deg 3
    ε**3,  # deg 3
    dP**2*ε,  # deg 3
    Qx**2*ε + Qy**2*ε,  # deg 3
    Mx**2*ε + My**2*ε,  # deg 3
    dMz*dP*ε,  # deg 3
    Mx*Qx*ε + My*Qy*ε,  # deg 3
    Mx*Qx*dMz + My*Qy*dMz,  # deg 3
    dMz**2*dP,  # deg 3
    dP*ε**2,  # deg 3
    dP**3,  # deg 3
    Qx**2*dP + Qy**2*dP,  # deg 3
    Mx**2*dP + My**2*dP,  # deg 3
    Mx*My*Qx*Qy,  # deg 4
    dMz**4,  # deg 4
    Mx*Qx*dMz*dP + My*Qy*dMz*dP,  # deg 4
    dMz**2*ε**2,  # deg 4
    dMz**2*dP**2,  # deg 4
    Qx**2*dMz**2 + Qy**2*dMz**2,  # deg 4
    Mx**2*dMz**2 + My**2*dMz**2,  # deg 4
    ε**4,  # deg 4
    dP**2*ε**2,  # deg 4
    Qx**2*ε**2 + Qy**2*ε**2,  # deg 4
    Mx**2*ε**2 + My**2*ε**2,  # deg 4
    dP**4,  # deg 4
    Qx**2*dP**2 + Qy**2*dP**2,  # deg 4
    Mx**2*dP**2 + My**2*dP**2,  # deg 4
    Qx**4 + 2*Qx**2*Qy**2 + Qy**4,  # deg 4
    Mx**2*Qy**2 + My**2*Qx**2,  # deg 4
    Mx**2*Qx**2 + My**2*Qy**2,  # deg 4
    Mx**4 + 2*Mx**2*My**2 + My**4,  # deg 4
    dMz*dP*ε**2,  # deg 4
    Mx*Qx*ε**2 + My*Qy*ε**2,  # deg 4
    dMz*dP**3,  # deg 4
    Mx*Qx*dP**2 + My*Qy*dP**2,  # deg 4
    Qx**2*dMz*dP + Qy**2*dMz*dP,  # deg 4
    dMz**3*dP,  # deg 4
    Mx**2*dMz*dP + My**2*dMz*dP,  # deg 4
    Mx*Qx**3 + Mx*Qx*Qy**2 + My*Qx**2*Qy + My*Qy**3,  # deg 4
    Mx*Qx*dMz**2 + My*Qy*dMz**2,  # deg 4
    Mx**3*Qx + Mx**2*My*Qy + Mx*My**2*Qx + My**3*Qy,  # deg 4
    dMz*ε**3,  # deg 4
    dMz*dP**2*ε,  # deg 4
    Mx*Qx*dP*ε + My*Qy*dP*ε,  # deg 4
    Qx**2*dMz*ε + Qy**2*dMz*ε,  # deg 4
    dMz**3*ε,  # deg 4
    Mx**2*dMz*ε + My**2*dMz*ε,  # deg 4
    dP*ε**3,  # deg 4
    dP**3*ε,  # deg 4
    Qx**2*dP*ε + Qy**2*dP*ε,  # deg 4
    dMz**2*dP*ε,  # deg 4
    Mx**2*dP*ε + My**2*dP*ε,  # deg 4
    Mx*Qx*dMz*ε + My*Qy*dMz*ε,  # deg 4
    Mx*My*Qx*Qy*dMz,  # deg 5
    Mx*My*Qx*Qy*dP,  # deg 5
    Mx*My*Qx*Qy*ε,  # deg 5
    Mx**2*Qy**2*dMz + My**2*Qx**2*dMz,  # deg 5
    dMz*ε**4,  # deg 5
    dMz*dP**2*ε**2,  # deg 5
    Mx*Qx*dP*ε**2 + My*Qy*dP*ε**2,  # deg 5
    Qx**2*dMz*ε**2 + Qy**2*dMz*ε**2,  # deg 5
    dMz**3*ε**2,  # deg 5
    Mx**2*dMz*ε**2 + My**2*dMz*ε**2,  # deg 5
    dMz*dP**4,  # deg 5
    Mx*Qx*dP**3 + My*Qy*dP**3,  # deg 5
    Qx**2*dMz*dP**2 + Qy**2*dMz*dP**2,  # deg 5
    dMz**3*dP**2,  # deg 5
    Mx**2*dMz*dP**2 + My**2*dMz*dP**2,  # deg 5
    Mx*Qx**3*dP + Mx*Qx*Qy**2*dP + My*Qx**2*Qy*dP + My*Qy**3*dP,  # deg 5
    Mx*Qx*dMz**2*dP + My*Qy*dMz**2*dP,  # deg 5
    Mx**3*Qx*dP + Mx**2*My*Qy*dP + Mx*My**2*Qx*dP + My**3*Qy*dP,  # deg 5
    Qx**4*dMz + 2*Qx**2*Qy**2*dMz + Qy**4*dMz,  # deg 5
    Qx**2*dMz**3 + Qy**2*dMz**3,  # deg 5
    Mx**2*Qx**2*dMz + My**2*Qy**2*dMz,  # deg 5
    dMz**5,  # deg 5
    Mx**2*dMz**3 + My**2*dMz**3,  # deg 5
    Mx**4*dMz + 2*Mx**2*My**2*dMz + My**4*dMz,  # deg 5
    Mx**2*Qy**2*dP + My**2*Qx**2*dP,  # deg 5
    dP*ε**4,  # deg 5
    dP**3*ε**2,  # deg 5
    Qx**2*dP*ε**2 + Qy**2*dP*ε**2,  # deg 5
    dMz**2*dP*ε**2,  # deg 5
    Mx**2*dP*ε**2 + My**2*dP*ε**2,  # deg 5
    Mx*Qx*dMz*ε**2 + My*Qy*dMz*ε**2,  # deg 5
    dP**5,  # deg 5
    Qx**2*dP**3 + Qy**2*dP**3,  # deg 5
    dMz**2*dP**3,  # deg 5
    Mx**2*dP**3 + My**2*dP**3,  # deg 5
    Mx*Qx*dMz*dP**2 + My*Qy*dMz*dP**2,  # deg 5
    Qx**4*dP + 2*Qx**2*Qy**2*dP + Qy**4*dP,  # deg 5
    Qx**2*dMz**2*dP + Qy**2*dMz**2*dP,  # deg 5
    Mx**2*Qx**2*dP + My**2*Qy**2*dP,  # deg 5
    dMz**4*dP,  # deg 5
    Mx**2*dMz**2*dP + My**2*dMz**2*dP,  # deg 5
    Mx**4*dP + 2*Mx**2*My**2*dP + My**4*dP,  # deg 5
    Mx*Qx**3*dMz + Mx*Qx*Qy**2*dMz + My*Qx**2*Qy*dMz + My*Qy**3*dMz,  # deg 5
    Mx*Qx*dMz**3 + My*Qy*dMz**3,  # deg 5
    Mx**3*Qx*dMz + Mx**2*My*Qy*dMz + Mx*My**2*Qx*dMz + My**3*Qy*dMz,  # deg 5
    ε**5,  # deg 5
    dP**2*ε**3,  # deg 5
    Qx**2*ε**3 + Qy**2*ε**3,  # deg 5
    dMz**2*ε**3,  # deg 5
    Mx**2*ε**3 + My**2*ε**3,  # deg 5
    dP**4*ε,  # deg 5
    Qx**2*dP**2*ε + Qy**2*dP**2*ε,  # deg 5
    dMz**2*dP**2*ε,  # deg 5
    Mx**2*dP**2*ε + My**2*dP**2*ε,  # deg 5
    Mx*Qx*dMz*dP*ε + My*Qy*dMz*dP*ε,  # deg 5
    Qx**4*ε + 2*Qx**2*Qy**2*ε + Qy**4*ε,  # deg 5
    Qx**2*dMz**2*ε + Qy**2*dMz**2*ε,  # deg 5
    Mx**2*Qx**2*ε + My**2*Qy**2*ε,  # deg 5
    Mx**2*Qy**2*ε + My**2*Qx**2*ε,  # deg 5
    dMz**4*ε,  # deg 5
    Mx**2*dMz**2*ε + My**2*dMz**2*ε,  # deg 5
    Mx**4*ε + 2*Mx**2*My**2*ε + My**4*ε,  # deg 5
    Mx*My*Qx*Qy*ε**2,  # deg 6
    Mx*My*Qx*Qy*dP**2,  # deg 6
    Mx*My*Qx*Qy**3,  # deg 6
    Mx*My*Qx**3*Qy,  # deg 6
    Mx*My*Qx*Qy*dMz**2,  # deg 6
    Mx*My**3*Qx*Qy,  # deg 6
    Mx**3*My*Qx*Qy,  # deg 6
    My**2*Qx**2*Qy**2,  # deg 6
    Mx**2*Qx**2*Qy**2,  # deg 6
    Mx**2*My**2*Qy**2,  # deg 6
    Mx**2*My**2*Qx**2,  # deg 6
    ε**6,  # deg 6
    dP**2*ε**4,  # deg 6
    Qx**2*ε**4 + Qy**2*ε**4,  # deg 6
    dMz**2*ε**4,  # deg 6
    Mx**2*ε**4 + My**2*ε**4,  # deg 6
    dP**4*ε**2,  # deg 6
    Qx**2*dP**2*ε**2 + Qy**2*dP**2*ε**2,  # deg 6
    dMz**2*dP**2*ε**2,  # deg 6
    Mx**2*dP**2*ε**2 + My**2*dP**2*ε**2,  # deg 6
    Mx*Qx*dMz*dP*ε**2 + My*Qy*dMz*dP*ε**2,  # deg 6
    Qx**4*ε**2 + 2*Qx**2*Qy**2*ε**2 + Qy**4*ε**2,  # deg 6
    Qx**2*dMz**2*ε**2 + Qy**2*dMz**2*ε**2,  # deg 6
    Mx**2*Qx**2*ε**2 + My**2*Qy**2*ε**2,  # deg 6
    Mx**2*Qy**2*ε**2 + My**2*Qx**2*ε**2,  # deg 6
    dMz**4*ε**2,  # deg 6
    Mx**2*dMz**2*ε**2 + My**2*dMz**2*ε**2,  # deg 6
    Mx**4*ε**2 + 2*Mx**2*My**2*ε**2 + My**4*ε**2,  # deg 6
    dP**6,  # deg 6
    Qx**2*dP**4 + Qy**2*dP**4,  # deg 6
    dMz**2*dP**4,  # deg 6
    Mx**2*dP**4 + My**2*dP**4,  # deg 6
    Mx*Qx*dMz*dP**3 + My*Qy*dMz*dP**3,  # deg 6
    Qx**4*dP**2 + 2*Qx**2*Qy**2*dP**2 + Qy**4*dP**2,  # deg 6
    Qx**2*dMz**2*dP**2 + Qy**2*dMz**2*dP**2,  # deg 6
    Mx**2*Qy**2*dP**2 + My**2*Qx**2*dP**2,  # deg 6
    Mx**2*Qx**2*dP**2 + My**2*Qy**2*dP**2,  # deg 6
    dMz**4*dP**2,  # deg 6
    Mx**2*dMz**2*dP**2 + My**2*dMz**2*dP**2,  # deg 6
    Mx**4*dP**2 + 2*Mx**2*My**2*dP**2 + My**4*dP**2,  # deg 6
    Mx*Qx**3*dMz*dP + Mx*Qx*Qy**2*dMz*dP + My*Qx**2*Qy*dMz*dP + My*Qy**3*dMz*dP,  # deg 6
    Mx*Qx*dMz**3*dP + My*Qy*dMz**3*dP,  # deg 6
    Mx**3*Qx*dMz*dP + Mx**2*My*Qy*dMz*dP + Mx*My**2*Qx*dMz*dP + My**3*Qy*dMz*dP,  # deg 6
    Qx**6,  # deg 6
    Qx**2*Qy**4,  # deg 6
    Qx**4*Qy**2,  # deg 6
    Qy**6,  # deg 6
    Qx**4*dMz**2 + 2*Qx**2*Qy**2*dMz**2 + Qy**4*dMz**2,  # deg 6
    Mx**2*Qx**4,  # deg 6
    My**2*Qy**4,  # deg 6
    Mx**2*Qy**4,  # deg 6
    My**2*Qx**4,  # deg 6
    Qx**2*dMz**4 + Qy**2*dMz**4,  # deg 6
    Mx**2*Qx**2*dMz**2 + My**2*Qy**2*dMz**2,  # deg 6
    Mx**2*Qy**2*dMz**2 + My**2*Qx**2*dMz**2,  # deg 6
    Mx**4*Qx**2,  # deg 6
    My**4*Qy**2,  # deg 6
    My**4*Qx**2,  # deg 6
    Mx**4*Qy**2,  # deg 6
    dMz**6,  # deg 6
    Mx**2*dMz**4 + My**2*dMz**4,  # deg 6
    Mx**4*dMz**2 + 2*Mx**2*My**2*dMz**2 + My**4*dMz**2,  # deg 6
    Mx**6,  # deg 6
    Mx**2*My**4,  # deg 6
    Mx**4*My**2,  # deg 6
    My**6,  # deg 6
]

# Condensed free energy
F = (
    beta1 * (1) +
    beta2 * (dMz) +
    beta3 * (ε) +
    beta4 * (dP) +
    beta5 * (dMz**2) +
    beta6 * (dMz*ε) +
    beta7 * (ε**2) +
    beta8 * (dP**2) +
    beta9 * (Qx**2 + Qy**2) +
    beta10 * (Mx**2 + My**2) +
    beta11 * (dMz*dP) +
    beta12 * (Mx*Qx + My*Qy) +
    beta13 * (dP*ε) +
    beta14 * (dMz**2*ε) +
    beta15 * (dMz*ε**2) +
    beta16 * (dMz*dP**2) +
    beta17 * (Qx**2*dMz + Qy**2*dMz) +
    beta18 * (Mx**2*dMz + My**2*dMz) +
    beta19 * (dMz**3) +
    beta20 * (Mx*Qx*dP + My*Qy*dP) +
    beta21 * (ε**3) +
    beta22 * (dP**2*ε) +
    beta23 * (Qx**2*ε + Qy**2*ε) +
    beta24 * (Mx**2*ε + My**2*ε) +
    beta25 * (dMz*dP*ε) +
    beta26 * (Mx*Qx*ε + My*Qy*ε) +
    beta27 * (Mx*Qx*dMz + My*Qy*dMz) +
    beta28 * (dMz**2*dP) +
    beta29 * (dP*ε**2) +
    beta30 * (dP**3) +
    beta31 * (Qx**2*dP + Qy**2*dP) +
    beta32 * (Mx**2*dP + My**2*dP) +
    beta33 * (Mx*My*Qx*Qy) +
    beta34 * (dMz**4) +
    beta35 * (Mx*Qx*dMz*dP + My*Qy*dMz*dP) +
    beta36 * (dMz**2*ε**2) +
    beta37 * (dMz**2*dP**2) +
    beta38 * (Qx**2*dMz**2 + Qy**2*dMz**2) +
    beta39 * (Mx**2*dMz**2 + My**2*dMz**2) +
    beta40 * (ε**4) +
    beta41 * (dP**2*ε**2) +
    beta42 * (Qx**2*ε**2 + Qy**2*ε**2) +
    beta43 * (Mx**2*ε**2 + My**2*ε**2) +
    beta44 * (dP**4) +
    beta45 * (Qx**2*dP**2 + Qy**2*dP**2) +
    beta46 * (Mx**2*dP**2 + My**2*dP**2) +
    beta47 * (Qx**4 + 2*Qx**2*Qy**2 + Qy**4) +
    beta48 * (Mx**2*Qy**2 + My**2*Qx**2) +
    beta49 * (Mx**2*Qx**2 + My**2*Qy**2) +
    beta50 * (Mx**4 + 2*Mx**2*My**2 + My**4) +
    beta51 * (dMz*dP*ε**2) +
    beta52 * (Mx*Qx*ε**2 + My*Qy*ε**2) +
    beta53 * (dMz*dP**3) +
    beta54 * (Mx*Qx*dP**2 + My*Qy*dP**2) +
    beta55 * (Qx**2*dMz*dP + Qy**2*dMz*dP) +
    beta56 * (dMz**3*dP) +
    beta57 * (Mx**2*dMz*dP + My**2*dMz*dP) +
    beta58 * (Mx*Qx**3 + Mx*Qx*Qy**2 + My*Qx**2*Qy + My*Qy**3) +
    beta59 * (Mx*Qx*dMz**2 + My*Qy*dMz**2) +
    beta60 * (Mx**3*Qx + Mx**2*My*Qy + Mx*My**2*Qx + My**3*Qy) +
    beta61 * (dMz*ε**3) +
    beta62 * (dMz*dP**2*ε) +
    beta63 * (Mx*Qx*dP*ε + My*Qy*dP*ε) +
    beta64 * (Qx**2*dMz*ε + Qy**2*dMz*ε) +
    beta65 * (dMz**3*ε) +
    beta66 * (Mx**2*dMz*ε + My**2*dMz*ε) +
    beta67 * (dP*ε**3) +
    beta68 * (dP**3*ε) +
    beta69 * (Qx**2*dP*ε + Qy**2*dP*ε) +
    beta70 * (dMz**2*dP*ε) +
    beta71 * (Mx**2*dP*ε + My**2*dP*ε) +
    beta72 * (Mx*Qx*dMz*ε + My*Qy*dMz*ε) +
    beta73 * (Mx*My*Qx*Qy*dMz) +
    beta74 * (Mx*My*Qx*Qy*dP) +
    beta75 * (Mx*My*Qx*Qy*ε) +
    beta76 * (Mx**2*Qy**2*dMz + My**2*Qx**2*dMz) +
    beta77 * (dMz*ε**4) +
    beta78 * (dMz*dP**2*ε**2) +
    beta79 * (Mx*Qx*dP*ε**2 + My*Qy*dP*ε**2) +
    beta80 * (Qx**2*dMz*ε**2 + Qy**2*dMz*ε**2) +
    beta81 * (dMz**3*ε**2) +
    beta82 * (Mx**2*dMz*ε**2 + My**2*dMz*ε**2) +
    beta83 * (dMz*dP**4) +
    beta84 * (Mx*Qx*dP**3 + My*Qy*dP**3) +
    beta85 * (Qx**2*dMz*dP**2 + Qy**2*dMz*dP**2) +
    beta86 * (dMz**3*dP**2) +
    beta87 * (Mx**2*dMz*dP**2 + My**2*dMz*dP**2) +
    beta88 * (Mx*Qx**3*dP + Mx*Qx*Qy**2*dP + My*Qx**2*Qy*dP + My*Qy**3*dP) +
    beta89 * (Mx*Qx*dMz**2*dP + My*Qy*dMz**2*dP) +
    beta90 * (Mx**3*Qx*dP + Mx**2*My*Qy*dP + Mx*My**2*Qx*dP + My**3*Qy*dP) +
    beta91 * (Qx**4*dMz + 2*Qx**2*Qy**2*dMz + Qy**4*dMz) +
    beta92 * (Qx**2*dMz**3 + Qy**2*dMz**3) +
    beta93 * (Mx**2*Qx**2*dMz + My**2*Qy**2*dMz) +
    beta94 * (dMz**5) +
    beta95 * (Mx**2*dMz**3 + My**2*dMz**3) +
    beta96 * (Mx**4*dMz + 2*Mx**2*My**2*dMz + My**4*dMz) +
    beta97 * (Mx**2*Qy**2*dP + My**2*Qx**2*dP) +
    beta98 * (dP*ε**4) +
    beta99 * (dP**3*ε**2) +
    beta100 * (Qx**2*dP*ε**2 + Qy**2*dP*ε**2) +
    beta101 * (dMz**2*dP*ε**2) +
    beta102 * (Mx**2*dP*ε**2 + My**2*dP*ε**2) +
    beta103 * (Mx*Qx*dMz*ε**2 + My*Qy*dMz*ε**2) +
    beta104 * (dP**5) +
    beta105 * (Qx**2*dP**3 + Qy**2*dP**3) +
    beta106 * (dMz**2*dP**3) +
    beta107 * (Mx**2*dP**3 + My**2*dP**3) +
    beta108 * (Mx*Qx*dMz*dP**2 + My*Qy*dMz*dP**2) +
    beta109 * (Qx**4*dP + 2*Qx**2*Qy**2*dP + Qy**4*dP) +
    beta110 * (Qx**2*dMz**2*dP + Qy**2*dMz**2*dP) +
    beta111 * (Mx**2*Qx**2*dP + My**2*Qy**2*dP) +
    beta112 * (dMz**4*dP) +
    beta113 * (Mx**2*dMz**2*dP + My**2*dMz**2*dP) +
    beta114 * (Mx**4*dP + 2*Mx**2*My**2*dP + My**4*dP) +
    beta115 * (Mx*Qx**3*dMz + Mx*Qx*Qy**2*dMz + My*Qx**2*Qy*dMz + My*Qy**3*dMz) +
    beta116 * (Mx*Qx*dMz**3 + My*Qy*dMz**3) +
    beta117 * (Mx**3*Qx*dMz + Mx**2*My*Qy*dMz + Mx*My**2*Qx*dMz + My**3*Qy*dMz) +
    beta118 * (ε**5) +
    beta119 * (dP**2*ε**3) +
    beta120 * (Qx**2*ε**3 + Qy**2*ε**3) +
    beta121 * (dMz**2*ε**3) +
    beta122 * (Mx**2*ε**3 + My**2*ε**3) +
    beta123 * (dP**4*ε) +
    beta124 * (Qx**2*dP**2*ε + Qy**2*dP**2*ε) +
    beta125 * (dMz**2*dP**2*ε) +
    beta126 * (Mx**2*dP**2*ε + My**2*dP**2*ε) +
    beta127 * (Mx*Qx*dMz*dP*ε + My*Qy*dMz*dP*ε) +
    beta128 * (Qx**4*ε + 2*Qx**2*Qy**2*ε + Qy**4*ε) +
    beta129 * (Qx**2*dMz**2*ε + Qy**2*dMz**2*ε) +
    beta130 * (Mx**2*Qx**2*ε + My**2*Qy**2*ε) +
    beta131 * (Mx**2*Qy**2*ε + My**2*Qx**2*ε) +
    beta132 * (dMz**4*ε) +
    beta133 * (Mx**2*dMz**2*ε + My**2*dMz**2*ε) +
    beta134 * (Mx**4*ε + 2*Mx**2*My**2*ε + My**4*ε) +
    beta135 * (Mx*My*Qx*Qy*ε**2) +
    beta136 * (Mx*My*Qx*Qy*dP**2) +
    beta137 * (Mx*My*Qx*Qy**3) +
    beta138 * (Mx*My*Qx**3*Qy) +
    beta139 * (Mx*My*Qx*Qy*dMz**2) +
    beta140 * (Mx*My**3*Qx*Qy) +
    beta141 * (Mx**3*My*Qx*Qy) +
    beta142 * (My**2*Qx**2*Qy**2) +
    beta143 * (Mx**2*Qx**2*Qy**2) +
    beta144 * (Mx**2*My**2*Qy**2) +
    beta145 * (Mx**2*My**2*Qx**2) +
    beta146 * (ε**6) +
    beta147 * (dP**2*ε**4) +
    beta148 * (Qx**2*ε**4 + Qy**2*ε**4) +
    beta149 * (dMz**2*ε**4) +
    beta150 * (Mx**2*ε**4 + My**2*ε**4) +
    beta151 * (dP**4*ε**2) +
    beta152 * (Qx**2*dP**2*ε**2 + Qy**2*dP**2*ε**2) +
    beta153 * (dMz**2*dP**2*ε**2) +
    beta154 * (Mx**2*dP**2*ε**2 + My**2*dP**2*ε**2) +
    beta155 * (Mx*Qx*dMz*dP*ε**2 + My*Qy*dMz*dP*ε**2) +
    beta156 * (Qx**4*ε**2 + 2*Qx**2*Qy**2*ε**2 + Qy**4*ε**2) +
    beta157 * (Qx**2*dMz**2*ε**2 + Qy**2*dMz**2*ε**2) +
    beta158 * (Mx**2*Qx**2*ε**2 + My**2*Qy**2*ε**2) +
    beta159 * (Mx**2*Qy**2*ε**2 + My**2*Qx**2*ε**2) +
    beta160 * (dMz**4*ε**2) +
    beta161 * (Mx**2*dMz**2*ε**2 + My**2*dMz**2*ε**2) +
    beta162 * (Mx**4*ε**2 + 2*Mx**2*My**2*ε**2 + My**4*ε**2) +
    beta163 * (dP**6) +
    beta164 * (Qx**2*dP**4 + Qy**2*dP**4) +
    beta165 * (dMz**2*dP**4) +
    beta166 * (Mx**2*dP**4 + My**2*dP**4) +
    beta167 * (Mx*Qx*dMz*dP**3 + My*Qy*dMz*dP**3) +
    beta168 * (Qx**4*dP**2 + 2*Qx**2*Qy**2*dP**2 + Qy**4*dP**2) +
    beta169 * (Qx**2*dMz**2*dP**2 + Qy**2*dMz**2*dP**2) +
    beta170 * (Mx**2*Qy**2*dP**2 + My**2*Qx**2*dP**2) +
    beta171 * (Mx**2*Qx**2*dP**2 + My**2*Qy**2*dP**2) +
    beta172 * (dMz**4*dP**2) +
    beta173 * (Mx**2*dMz**2*dP**2 + My**2*dMz**2*dP**2) +
    beta174 * (Mx**4*dP**2 + 2*Mx**2*My**2*dP**2 + My**4*dP**2) +
    beta175 * (Mx*Qx**3*dMz*dP + Mx*Qx*Qy**2*dMz*dP + My*Qx**2*Qy*dMz*dP + My*Qy**3*dMz*dP) +
    beta176 * (Mx*Qx*dMz**3*dP + My*Qy*dMz**3*dP) +
    beta177 * (Mx**3*Qx*dMz*dP + Mx**2*My*Qy*dMz*dP + Mx*My**2*Qx*dMz*dP + My**3*Qy*dMz*dP) +
    beta178 * (Qx**6) +
    beta179 * (Qx**2*Qy**4) +
    beta180 * (Qx**4*Qy**2) +
    beta181 * (Qy**6) +
    beta182 * (Qx**4*dMz**2 + 2*Qx**2*Qy**2*dMz**2 + Qy**4*dMz**2) +
    beta183 * (Mx**2*Qx**4) +
    beta184 * (My**2*Qy**4) +
    beta185 * (Mx**2*Qy**4) +
    beta186 * (My**2*Qx**4) +
    beta187 * (Qx**2*dMz**4 + Qy**2*dMz**4) +
    beta188 * (Mx**2*Qx**2*dMz**2 + My**2*Qy**2*dMz**2) +
    beta189 * (Mx**2*Qy**2*dMz**2 + My**2*Qx**2*dMz**2) +
    beta190 * (Mx**4*Qx**2) +
    beta191 * (My**4*Qy**2) +
    beta192 * (My**4*Qx**2) +
    beta193 * (Mx**4*Qy**2) +
    beta194 * (dMz**6) +
    beta195 * (Mx**2*dMz**4 + My**2*dMz**4) +
    beta196 * (Mx**4*dMz**2 + 2*Mx**2*My**2*dMz**2 + My**4*dMz**2) +
    beta197 * (Mx**6) +
    beta198 * (Mx**2*My**4) +
    beta199 * (Mx**4*My**2) +
    beta200 * (My**6)
)

