"""
Condensed invariant polynomials
Source: output
Condensation: P -> P0+dP, Mz -> Mz0+dMz
Generated by isocond
"""

import sympy as sp

# Original coefficient symbols
alpha1, alpha2, alpha3, alpha4, alpha5, alpha6, alpha7, alpha8, alpha9, alpha10, alpha11, alpha12, alpha13, alpha14, alpha15, alpha16, alpha17, alpha18, alpha19, alpha20, alpha21, alpha22, alpha23, alpha24, alpha25, alpha26, alpha27, alpha28, alpha29, alpha30, alpha31, alpha32, alpha33, alpha34, alpha35, alpha36, alpha37, alpha38, alpha39, alpha40, alpha41, alpha42, alpha43, alpha44, alpha45, alpha46, alpha47, alpha48, alpha49, alpha50, alpha51, alpha52, alpha53, alpha54, alpha55, alpha56, alpha57, alpha58, alpha59, alpha60, alpha61, alpha62, alpha63, alpha64, alpha65, alpha66, alpha67, alpha68, alpha69, alpha70, alpha71, alpha72, alpha73, alpha74, alpha75, alpha76, alpha77, alpha78, alpha79, alpha80, alpha81, alpha82, alpha83, alpha84, alpha85, alpha86, alpha87, alpha88, alpha89, alpha90, alpha91, alpha92, alpha93, alpha94 = sp.symbols("alpha1 alpha2 alpha3 alpha4 alpha5 alpha6 alpha7 alpha8 alpha9 alpha10 alpha11 alpha12 alpha13 alpha14 alpha15 alpha16 alpha17 alpha18 alpha19 alpha20 alpha21 alpha22 alpha23 alpha24 alpha25 alpha26 alpha27 alpha28 alpha29 alpha30 alpha31 alpha32 alpha33 alpha34 alpha35 alpha36 alpha37 alpha38 alpha39 alpha40 alpha41 alpha42 alpha43 alpha44 alpha45 alpha46 alpha47 alpha48 alpha49 alpha50 alpha51 alpha52 alpha53 alpha54 alpha55 alpha56 alpha57 alpha58 alpha59 alpha60 alpha61 alpha62 alpha63 alpha64 alpha65 alpha66 alpha67 alpha68 alpha69 alpha70 alpha71 alpha72 alpha73 alpha74 alpha75 alpha76 alpha77 alpha78 alpha79 alpha80 alpha81 alpha82 alpha83 alpha84 alpha85 alpha86 alpha87 alpha88 alpha89 alpha90 alpha91 alpha92 alpha93 alpha94")

# Static (condensed) variable symbols
P0, Mz0 = sp.symbols("P0 Mz0")

# Dynamic variable symbols
dP, dMz, ε, Qx, Qy, Mx, My = sp.symbols("dP dMz ε Qx Qy Mx My")

# New effective coefficients
beta1 = 2*Mz0*alpha5
beta2 = alpha1
beta3 = 2*P0*alpha3
beta4 = alpha5
beta5 = 2*Mz0*alpha10
beta6 = alpha2
beta7 = alpha3
beta8 = alpha4
beta9 = alpha6
beta10 = 4*Mz0*P0*alpha19
beta11 = Mz0*P0*alpha21
beta12 = 2*P0*alpha8
beta13 = alpha10
beta14 = 2*Mz0*alpha15
beta15 = 2*Mz0*alpha19
beta16 = 2*Mz0*alpha23
beta17 = 2*Mz0*alpha27
beta18 = 4*Mz0*alpha26
beta19 = Mz0*alpha21
beta20 = alpha7
beta21 = alpha8
beta22 = alpha9
beta23 = alpha11
beta24 = 4*Mz0*P0*alpha36
beta25 = Mz0*P0*alpha38
beta26 = P0*alpha21
beta27 = 2*P0*alpha19
beta28 = 2*P0*alpha13
beta29 = 4*P0*alpha17
beta30 = 2*P0*alpha18
beta31 = 2*P0*alpha20

# New invariants
invariants = [
    dMz,  # deg 1
    ε,  # deg 1
    dP,  # deg 1
    dMz**2,  # deg 2
    dMz*ε,  # deg 2
    ε**2,  # deg 2
    dP**2,  # deg 2
    Qx**2 + Qy**2,  # deg 2
    Mx**2 + My**2,  # deg 2
    dMz*dP,  # deg 2
    Mx*Qx + My*Qy,  # deg 2
    dP*ε,  # deg 2
    dMz**2*ε,  # deg 3
    dMz*ε**2,  # deg 3
    dMz*dP**2,  # deg 3
    Qx**2*dMz + Qy**2*dMz,  # deg 3
    Mx**2*dMz + My**2*dMz,  # deg 3
    dMz**3,  # deg 3
    Mx*Qx*dP + My*Qy*dP,  # deg 3
    ε**3,  # deg 3
    dP**2*ε,  # deg 3
    Qx**2*ε + Qy**2*ε,  # deg 3
    Mx**2*ε + My**2*ε,  # deg 3
    dMz*dP*ε,  # deg 3
    Mx*Qx*ε + My*Qy*ε,  # deg 3
    Mx*Qx*dMz + My*Qy*dMz,  # deg 3
    dMz**2*dP,  # deg 3
    dP*ε**2,  # deg 3
    dP**3,  # deg 3
    Qx**2*dP + Qy**2*dP,  # deg 3
    Mx**2*dP + My**2*dP,  # deg 3
]

# Condensed free energy
F = (
    beta1 * (dMz) +
    beta2 * (ε) +
    beta3 * (dP) +
    beta4 * (dMz**2) +
    beta5 * (dMz*ε) +
    beta6 * (ε**2) +
    beta7 * (dP**2) +
    beta8 * (Qx**2 + Qy**2) +
    beta9 * (Mx**2 + My**2) +
    beta10 * (dMz*dP) +
    beta11 * (Mx*Qx + My*Qy) +
    beta12 * (dP*ε) +
    beta13 * (dMz**2*ε) +
    beta14 * (dMz*ε**2) +
    beta15 * (dMz*dP**2) +
    beta16 * (Qx**2*dMz + Qy**2*dMz) +
    beta17 * (Mx**2*dMz + My**2*dMz) +
    beta18 * (dMz**3) +
    beta19 * (Mx*Qx*dP + My*Qy*dP) +
    beta20 * (ε**3) +
    beta21 * (dP**2*ε) +
    beta22 * (Qx**2*ε + Qy**2*ε) +
    beta23 * (Mx**2*ε + My**2*ε) +
    beta24 * (dMz*dP*ε) +
    beta25 * (Mx*Qx*ε + My*Qy*ε) +
    beta26 * (Mx*Qx*dMz + My*Qy*dMz) +
    beta27 * (dMz**2*dP) +
    beta28 * (dP*ε**2) +
    beta29 * (dP**3) +
    beta30 * (Qx**2*dP + Qy**2*dP) +
    beta31 * (Mx**2*dP + My**2*dP)
)

