"""
Condensed invariant polynomials
Source: output
Condensation: P -> P0+dP, Mz -> Mz0+dMz
Generated by isocond
"""

import sympy as sp

# Original coefficient symbols
alpha1, alpha2, alpha3, alpha4, alpha5, alpha6, alpha7, alpha8, alpha9, alpha10, alpha11, alpha12, alpha13, alpha14, alpha15, alpha16, alpha17, alpha18, alpha19, alpha20, alpha21, alpha22, alpha23, alpha24, alpha25, alpha26, alpha27, alpha28, alpha29, alpha30, alpha31, alpha32, alpha33, alpha34, alpha35, alpha36, alpha37, alpha38, alpha39, alpha40, alpha41, alpha42, alpha43, alpha44, alpha45, alpha46, alpha47, alpha48, alpha49, alpha50, alpha51, alpha52, alpha53, alpha54, alpha55, alpha56, alpha57, alpha58, alpha59, alpha60, alpha61, alpha62, alpha63, alpha64, alpha65, alpha66, alpha67, alpha68, alpha69, alpha70, alpha71, alpha72, alpha73, alpha74, alpha75, alpha76, alpha77, alpha78, alpha79, alpha80, alpha81, alpha82, alpha83, alpha84, alpha85, alpha86, alpha87, alpha88, alpha89, alpha90, alpha91, alpha92, alpha93, alpha94 = sp.symbols("alpha1 alpha2 alpha3 alpha4 alpha5 alpha6 alpha7 alpha8 alpha9 alpha10 alpha11 alpha12 alpha13 alpha14 alpha15 alpha16 alpha17 alpha18 alpha19 alpha20 alpha21 alpha22 alpha23 alpha24 alpha25 alpha26 alpha27 alpha28 alpha29 alpha30 alpha31 alpha32 alpha33 alpha34 alpha35 alpha36 alpha37 alpha38 alpha39 alpha40 alpha41 alpha42 alpha43 alpha44 alpha45 alpha46 alpha47 alpha48 alpha49 alpha50 alpha51 alpha52 alpha53 alpha54 alpha55 alpha56 alpha57 alpha58 alpha59 alpha60 alpha61 alpha62 alpha63 alpha64 alpha65 alpha66 alpha67 alpha68 alpha69 alpha70 alpha71 alpha72 alpha73 alpha74 alpha75 alpha76 alpha77 alpha78 alpha79 alpha80 alpha81 alpha82 alpha83 alpha84 alpha85 alpha86 alpha87 alpha88 alpha89 alpha90 alpha91 alpha92 alpha93 alpha94")

# Static (condensed) variable symbols
P0, Mz0 = sp.symbols("P0 Mz0")

# Dynamic variable symbols
dP, dMz, ε, Qx, Qy, Mx, My = sp.symbols("dP dMz ε Qx Qy Mx My")

# New effective coefficients
beta1 = Mz0**6*alpha90 + Mz0**4*P0**2*alpha72 + Mz0**4*alpha26 + Mz0**2*P0**4*alpha65 + Mz0**2*P0**2*alpha19 + Mz0**2*alpha5 + P0**6*alpha63 + P0**4*alpha17 + P0**2*alpha3
beta2 = 2*Mz0*(3*Mz0**4*alpha90 + 2*Mz0**2*P0**2*alpha72 + 2*Mz0**2*alpha26 + P0**4*alpha65 + P0**2*alpha19 + alpha5)
beta3 = Mz0**4*alpha43 + Mz0**2*P0**2*alpha36 + Mz0**2*alpha10 + P0**4*alpha34 + P0**2*alpha8 + alpha1
beta4 = 2*P0*(Mz0**4*alpha72 + 2*Mz0**2*P0**2*alpha65 + Mz0**2*alpha19 + 3*P0**4*alpha63 + 2*P0**2*alpha17 + alpha3)
beta5 = 15*Mz0**4*alpha90 + 6*Mz0**2*P0**2*alpha72 + 6*Mz0**2*alpha26 + P0**4*alpha65 + P0**2*alpha19 + alpha5
beta6 = 2*Mz0*(2*Mz0**2*alpha43 + P0**2*alpha36 + alpha10)
beta7 = Mz0**4*alpha60 + Mz0**2*P0**2*alpha53 + Mz0**2*alpha15 + P0**4*alpha51 + P0**2*alpha13 + alpha2
beta8 = Mz0**4*alpha72 + 6*Mz0**2*P0**2*alpha65 + Mz0**2*alpha19 + 15*P0**4*alpha63 + 6*P0**2*alpha17 + alpha3
beta9 = Mz0**4*alpha84 + Mz0**2*P0**2*alpha69 + Mz0**2*alpha23 + P0**4*alpha64 + P0**2*alpha18 + alpha4
beta10 = Mz0**4*alpha91 + Mz0**2*P0**2*alpha73 + Mz0**2*alpha27 + P0**4*alpha66 + P0**2*alpha20 + alpha6
beta11 = 4*Mz0*P0*(2*Mz0**2*alpha72 + 2*P0**2*alpha65 + alpha19)
beta12 = Mz0*P0*(Mz0**2*alpha76 + P0**2*alpha67 + alpha21)
beta13 = 2*P0*(Mz0**2*alpha36 + 2*P0**2*alpha34 + alpha8)
beta14 = 6*Mz0**2*alpha43 + P0**2*alpha36 + alpha10
beta15 = 2*Mz0*(2*Mz0**2*alpha60 + P0**2*alpha53 + alpha15)
beta16 = 2*Mz0*(2*Mz0**2*alpha72 + 6*P0**2*alpha65 + alpha19)
beta17 = 2*Mz0*(2*Mz0**2*alpha84 + P0**2*alpha69 + alpha23)
beta18 = 2*Mz0*(2*Mz0**2*alpha91 + P0**2*alpha73 + alpha27)
beta19 = 4*Mz0*(5*Mz0**2*alpha90 + P0**2*alpha72 + alpha26)
beta20 = Mz0*(Mz0**2*alpha76 + 3*P0**2*alpha67 + alpha21)
beta21 = Mz0**2*alpha32 + P0**2*alpha30 + alpha7
beta22 = Mz0**2*alpha36 + 6*P0**2*alpha34 + alpha8
beta23 = Mz0**2*alpha40 + P0**2*alpha35 + alpha9
beta24 = Mz0**2*alpha44 + P0**2*alpha37 + alpha11
beta25 = 4*Mz0*P0*alpha36
beta26 = Mz0*P0*alpha38
beta27 = P0*(3*Mz0**2*alpha76 + P0**2*alpha67 + alpha21)
beta28 = 2*P0*(6*Mz0**2*alpha72 + 2*P0**2*alpha65 + alpha19)
beta29 = 2*P0*(Mz0**2*alpha53 + 2*P0**2*alpha51 + alpha13)
beta30 = 4*P0*(Mz0**2*alpha65 + 5*P0**2*alpha63 + alpha17)
beta31 = 2*P0*(Mz0**2*alpha69 + 2*P0**2*alpha64 + alpha18)
beta32 = 2*P0*(Mz0**2*alpha73 + 2*P0**2*alpha66 + alpha20)

# New invariants
invariants = [
    1,  # deg 0
    dMz,  # deg 1
    ε,  # deg 1
    dP,  # deg 1
    dMz**2,  # deg 2
    dMz*ε,  # deg 2
    ε**2,  # deg 2
    dP**2,  # deg 2
    Qx**2 + Qy**2,  # deg 2
    Mx**2 + My**2,  # deg 2
    dMz*dP,  # deg 2
    Mx*Qx + My*Qy,  # deg 2
    dP*ε,  # deg 2
    dMz**2*ε,  # deg 3
    dMz*ε**2,  # deg 3
    dMz*dP**2,  # deg 3
    Qx**2*dMz + Qy**2*dMz,  # deg 3
    Mx**2*dMz + My**2*dMz,  # deg 3
    dMz**3,  # deg 3
    Mx*Qx*dP + My*Qy*dP,  # deg 3
    ε**3,  # deg 3
    dP**2*ε,  # deg 3
    Qx**2*ε + Qy**2*ε,  # deg 3
    Mx**2*ε + My**2*ε,  # deg 3
    dMz*dP*ε,  # deg 3
    Mx*Qx*ε + My*Qy*ε,  # deg 3
    Mx*Qx*dMz + My*Qy*dMz,  # deg 3
    dMz**2*dP,  # deg 3
    dP*ε**2,  # deg 3
    dP**3,  # deg 3
    Qx**2*dP + Qy**2*dP,  # deg 3
    Mx**2*dP + My**2*dP,  # deg 3
]

# Condensed free energy
F = (
    beta1 * (1) +
    beta2 * (dMz) +
    beta3 * (ε) +
    beta4 * (dP) +
    beta5 * (dMz**2) +
    beta6 * (dMz*ε) +
    beta7 * (ε**2) +
    beta8 * (dP**2) +
    beta9 * (Qx**2 + Qy**2) +
    beta10 * (Mx**2 + My**2) +
    beta11 * (dMz*dP) +
    beta12 * (Mx*Qx + My*Qy) +
    beta13 * (dP*ε) +
    beta14 * (dMz**2*ε) +
    beta15 * (dMz*ε**2) +
    beta16 * (dMz*dP**2) +
    beta17 * (Qx**2*dMz + Qy**2*dMz) +
    beta18 * (Mx**2*dMz + My**2*dMz) +
    beta19 * (dMz**3) +
    beta20 * (Mx*Qx*dP + My*Qy*dP) +
    beta21 * (ε**3) +
    beta22 * (dP**2*ε) +
    beta23 * (Qx**2*ε + Qy**2*ε) +
    beta24 * (Mx**2*ε + My**2*ε) +
    beta25 * (dMz*dP*ε) +
    beta26 * (Mx*Qx*ε + My*Qy*ε) +
    beta27 * (Mx*Qx*dMz + My*Qy*dMz) +
    beta28 * (dMz**2*dP) +
    beta29 * (dP*ε**2) +
    beta30 * (dP**3) +
    beta31 * (Qx**2*dP + Qy**2*dP) +
    beta32 * (Mx**2*dP + My**2*dP)
)

