"""
Invariant polynomials for space group 194
Irreps: GM1+, GM2-, GM6-, GM6-, mGM2+, mGM6+
Degree: 3
Generated by isoinv
"""

import sympy as sp

# Variable declarations
ε, P, Qx, Qy, Ex, Ey, Mz, Mx, My = sp.symbols("ε P Qx Qy Ex Ey Mz Mx My")

# Coefficient declarations
c1, c2, c3, c4, c5, c6, c7 = sp.symbols("c1 c2 c3 c4 c5 c6 c7")

# Individual invariants
invariants = [
    (ε)**3,  # deg 3
    (ε)*(P)**2,  # deg 3
    (ε)*(Qx)**2 +(ε)*(Qy)**2,  # deg 3
    (ε)*(Qx)*(Ex) +(ε)*(Qy)*(Ey),  # deg 3
    (ε)*(Ex)**2 +(ε)*(Ey)**2,  # deg 3
    (ε)*(Mz)**2,  # deg 3
    (ε)*(Mx)**2 +(ε)*(My)**2,  # deg 3
]

# Free energy expansion
F = (
    c1 * ((ε)**3) +
    c2 * ((ε)*(P)**2) +
    c3 * ((ε)*(Qx)**2 +(ε)*(Qy)**2) +
    c4 * ((ε)*(Qx)*(Ex) +(ε)*(Qy)*(Ey)) +
    c5 * ((ε)*(Ex)**2 +(ε)*(Ey)**2) +
    c6 * ((ε)*(Mz)**2) +
    c7 * ((ε)*(Mx)**2 +(ε)*(My)**2)
)
