"""
Invariant polynomials for space group 194
Irreps: GM2-, GM6-, mGM2+
Degree: 1-4
Generated by isoinv
"""

import sympy as sp

# Variable declarations
Pz, Qx, Qy, Mz = sp.symbols("Pz Qx Qy Mz")

# Coefficient declarations
c1, c2, c3, c4, c5, c6, c7, c8, c9 = sp.symbols("c1 c2 c3 c4 c5 c6 c7 c8 c9")

# Individual invariants
invariants = [
    (Pz)**2,  # deg 2
    (Qx)**2 +(Qy)**2,  # deg 2
    (Mz)**2,  # deg 2
    (Pz)**4,  # deg 4
    (Pz)**2*(Qx)**2 +(Pz)**2*(Qy)**2,  # deg 4
    (Pz)**2*(Mz)**2,  # deg 4
    (Qx)**4 +2*(Qx)**2*(Qy)**2 +(Qy)**4,  # deg 4
    (Qx)**2*(Mz)**2 +(Qy)**2*(Mz)**2,  # deg 4
    (Mz)**4,  # deg 4
]

# Free energy expansion
F = (
    c1 * ((Pz)**2) +
    c2 * ((Qx)**2 +(Qy)**2) +
    c3 * ((Mz)**2) +
    c4 * ((Pz)**4) +
    c5 * ((Pz)**2*(Qx)**2 +(Pz)**2*(Qy)**2) +
    c6 * ((Pz)**2*(Mz)**2) +
    c7 * ((Qx)**4 +2*(Qx)**2*(Qy)**2 +(Qy)**4) +
    c8 * ((Qx)**2*(Mz)**2 +(Qy)**2*(Mz)**2) +
    c9 * ((Mz)**4)
)
