"""
Condensed invariant polynomials
Source: output_test
Condensation: Pz -> Pz0+dPz
Generated by isocond
"""

import sympy as sp

# Original coefficient symbols
c1, c2, c3, c4, c5, c6, c7, c8, c9 = sp.symbols("c1 c2 c3 c4 c5 c6 c7 c8 c9")

# Static (condensed) variable symbols
Pz0 = sp.symbols("Pz0")

# Dynamic variable symbols
dPz, Qx, Qy, Mz = sp.symbols("dPz Qx Qy Mz")

# New effective coefficients
beta1 = Pz0**2*(Pz0**2*c4 + c1)
beta2 = 2*Pz0*(2*Pz0**2*c4 + c1)
beta3 = 6*Pz0**2*c4 + c1
beta4 = Pz0**2*c5 + c2
beta5 = Pz0**2*c6 + c3
beta6 = 4*Pz0*c4
beta7 = 2*Pz0*c5
beta8 = 2*Pz0*c6
beta9 = c4
beta10 = c5
beta11 = c6
beta12 = c7
beta13 = c8
beta14 = c9

# New invariants
invariants = [
    1,  # deg 0
    dPz,  # deg 1
    dPz**2,  # deg 2
    Qx**2 + Qy**2,  # deg 2
    Mz**2,  # deg 2
    dPz**3,  # deg 3
    Qx**2*dPz + Qy**2*dPz,  # deg 3
    Mz**2*dPz,  # deg 3
    dPz**4,  # deg 4
    Qx**2*dPz**2 + Qy**2*dPz**2,  # deg 4
    Mz**2*dPz**2,  # deg 4
    Qx**4 + 2*Qx**2*Qy**2 + Qy**4,  # deg 4
    Mz**2*Qx**2 + Mz**2*Qy**2,  # deg 4
    Mz**4,  # deg 4
]

# Condensed free energy
F = (
    beta1 * (1) +
    beta2 * (dPz) +
    beta3 * (dPz**2) +
    beta4 * (Qx**2 + Qy**2) +
    beta5 * (Mz**2) +
    beta6 * (dPz**3) +
    beta7 * (Qx**2*dPz + Qy**2*dPz) +
    beta8 * (Mz**2*dPz) +
    beta9 * (dPz**4) +
    beta10 * (Qx**2*dPz**2 + Qy**2*dPz**2) +
    beta11 * (Mz**2*dPz**2) +
    beta12 * (Qx**4 + 2*Qx**2*Qy**2 + Qy**4) +
    beta13 * (Mz**2*Qx**2 + Mz**2*Qy**2) +
    beta14 * (Mz**4)
)

