"""
output_py.py
Python (sympy-compatible) output for invariant polynomials.

Converts parenthesised substituted polynomials to valid Python/sympy expressions:
  - ^     ->  **       (exponent notation, first)
  - )^N(  ->  )**N*(   (adjacent terms with exponents)
  - )(    ->  )*(      (adjacent degree-1 terms)
  - N(    ->  N*(      (numeric coefficient before parenthesised term)
"""

import re
from typing import Dict, List, Optional, Tuple
from pathlib import Path


def _fmt(polynomial: str) -> str:
    """Convert to sympy-compatible Python expression."""
    # ^ -> ** first so subsequent patterns can match **N
    result = polynomial.replace('^', '**')
    # insert * between adjacent parenthesised tokens: )**N( and )(
    result = re.sub(r'\)(\*\*\d+)?\(', lambda m: ')' + (m.group(1) or '') + '*(', result)
    # insert * between numeric coefficient and opening paren: 2( -> 2*(
    result = re.sub(r'(\d)\(', r'\1*(', result)
    return result


def write_py(
    outpath: Path,
    parent: int,
    irreps: List[str],
    degree: Tuple[int, int],
    var_map: Dict[str, dict],
    invariants: List[dict],
    collapsed: Optional[List[dict]] = None,
    coeff_style: str = "c",
) -> None:
    deg_lo, deg_hi = degree
    deg_str = str(deg_lo) if deg_lo == deg_hi else f"{deg_lo}-{deg_hi}"
    all_vars = [info["code"] for info in var_map.values()]

    lines = []
    lines.append('"""')
    lines.append(f'Invariant polynomials for space group {parent}')
    lines.append(f'Irreps: {", ".join(irreps)}')
    lines.append(f'Degree: {deg_str}')
    lines.append(f'Generated by isoinv')
    lines.append('"""')
    lines.append('')
    lines.append('import sympy as sp')
    lines.append('')
    lines.append('# Variable declarations')
    lines.append(f'{", ".join(all_vars)} = sp.symbols("{" ".join(all_vars)}")')
    lines.append('')

    if collapsed:
        coeff_names = [f"{coeff_style}{i+1}" for i in range(len(collapsed))]
        lines.append('# Coefficient declarations')
        lines.append(f'{", ".join(coeff_names)} = sp.symbols("{" ".join(coeff_names)}")')
        lines.append('')

    lines.append('# Individual invariants')
    lines.append('invariants = [')
    for inv in invariants:
        lines.append(f'    {_fmt(inv["polynomial"])},  # deg {inv["degree"]}')
    lines.append(']')
    lines.append('')

    if collapsed:
        lines.append('# Free energy expansion')
        lines.append('F = (')
        for i, inv in enumerate(collapsed):
            sep = ' +' if i < len(collapsed) - 1 else ''
            lines.append(f'    {coeff_style}{i+1} * ({_fmt(inv["polynomial"])}){sep}')
        lines.append(')')
        lines.append('')

    outpath.write_text("\n".join(lines))
    print(f"  Written: {outpath}")
